// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ve6HzPa33HUxN1h55Rnv96WtWGR38fw',
    appId: '1:84295424976:web:a58652da6170a0844cf7d5',
    messagingSenderId: '84295424976',
    projectId: 'stamptourapp-436e1',
    authDomain: 'stamptourapp-436e1.firebaseapp.com',
    storageBucket: 'stamptourapp-436e1.firebasestorage.app',
    measurementId: 'G-R9J20FZNTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaHdKyQkDxbUkWYQl3yISGeF8KZE-Nof4',
    appId: '1:84295424976:android:2095f1adbd2992f44cf7d5',
    messagingSenderId: '84295424976',
    projectId: 'stamptourapp-436e1',
    storageBucket: 'stamptourapp-436e1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5l7DcNjd3rLWjMQ7RpY5JXsMWPJGqJgo',
    appId: '1:84295424976:ios:146b0a903eed9b654cf7d5',
    messagingSenderId: '84295424976',
    projectId: 'stamptourapp-436e1',
    storageBucket: 'stamptourapp-436e1.firebasestorage.app',
    iosBundleId: 'com.example.stampWayFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ve6HzPa33HUxN1h55Rnv96WtWGR38fw',
    appId: '1:84295424976:web:daad8e4f93cc7c054cf7d5',
    messagingSenderId: '84295424976',
    projectId: 'stamptourapp-436e1',
    authDomain: 'stamptourapp-436e1.firebaseapp.com',
    storageBucket: 'stamptourapp-436e1.firebasestorage.app',
    measurementId: 'G-ZD5WGT01SR',
  );
}
